<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ssitao.code</groupId>
        <artifactId>ssitao-code-frame</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ssitao-code-frame-aggregate</artifactId>
    <packaging>pom</packaging>

    <name>ssitao-code-frame-aggregate</name>
    <description>Aggregate Framework 模块 - 聚合框架</description>

    <modules>
        <module>aggregate-framework-parent</module>
        <module>aggregate-framework-dependencies</module>
        <module>aggregate-framework-bom</module>
        <module>aggregate-framework-core</module>
        <module>aggregate-framework-spring</module>
        <module>aggregate-framework-spring-boot-starter</module>
<!--        <module>aggregate-framework-admin-web</module>-->
        <module>aggregate-framework-dashboard</module>
        <module>aggregate-framework-server</module>
        <module>aggregate-framework-distribution</module>
        <module>aggregate-framework-tutorial-sample</module>
    </modules>
</project>
