-- 元数据表字段定义
CREATE TABLE meta_column (
    column_id         VARCHAR(64) NOT NULL COMMENT '字段ID' PRIMARY KEY,
    table_id          VARCHAR(64) NOT NULL COMMENT '表ID',
    column_name       VARCHAR(64) NOT NULL COMMENT '字段名称',
    column_desc       VARCHAR(256) COMMENT '字段描述',
    column_type       VARCHAR(32) NOT NULL COMMENT '字段类型',
    java_type         VARCHAR(64) NOT NULL COMMENT 'Java类型',
    java_field        VARCHAR(64) NOT NULL COMMENT 'Java字段名',
    is_pk             TINYINT(1) DEFAULT 0 COMMENT '是否主键',
    is_increment      TINYINT(1) DEFAULT 0 COMMENT '是否自增',
    is_required       TINYINT(1) DEFAULT 0 COMMENT '是否必填',
    is_query          TINYINT(1) DEFAULT 0 COMMENT '是否为查询条件',
    query_type        INT DEFAULT 1 COMMENT '查询方式:1-精确 2-模糊 3-范围',
    is_display        TINYINT(1) DEFAULT 0 COMMENT '是否为显示字段',
    is_list           TINYINT(1) DEFAULT 0 COMMENT '是否为列表显示',
    is_form           TINYINT(1) DEFAULT 0 COMMENT '是否为表单字段',
    form_type         INT DEFAULT 1 COMMENT '表单类型:1-文本框 2-文本域 3-下拉框 4-单选框 5-复选框 6-日期选择 7-文件上传 8-富文本',
    dict_type         VARCHAR(64) COMMENT '字典类型',
    default_value     VARCHAR(256) COMMENT '默认值',
    column_sort       INT DEFAULT 0 COMMENT '排序',
    remark            VARCHAR(512) COMMENT '备注',
    tenant_id         VARCHAR(64) DEFAULT 'default' COMMENT '租户ID',
    create_time       DATETIME COMMENT '创建时间',
    create_user_id    VARCHAR(64) COMMENT '创建人ID',
    modify_time       DATETIME COMMENT '修改时间',
    modify_user_id    VARCHAR(64) COMMENT '修改人ID',
    is_deleted        TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    version           INT DEFAULT 0 COMMENT '版本号',
    INDEX idx_table_id (table_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据表字段定义';
