-- 元数据列表配置
CREATE TABLE meta_list (
    list_id          VARCHAR(64) NOT NULL COMMENT '列表配置ID' PRIMARY KEY,
    entity_id        VARCHAR(64) NOT NULL COMMENT '实体ID',
    list_code        VARCHAR(64) NOT NULL COMMENT '列表编码',
    list_name        VARCHAR(128) NOT NULL COMMENT '列表名称',
    list_type        INT DEFAULT 1 COMMENT '列表类型:1-默认列表 2-树形列表 3-表格列表 4-分组列表',
    row_style        INT DEFAULT 3 COMMENT '列表行样式:1-默认 2-紧凑 3-舒适',
    stripe           TINYINT(1) DEFAULT 1 COMMENT '是否显示斑马纹',
    border           TINYINT(1) DEFAULT 1 COMMENT '是否显示边框',
    show_header      TINYINT(1) DEFAULT 1 COMMENT '是否显示表头',
    highlight_current_row TINYINT(1) DEFAULT 1 COMMENT '是否高亮当前行',
    sort_mode       INT DEFAULT 1 COMMENT '排序方式:1-服务端排序 2-客户端排序',
    default_sort_field VARCHAR(64) COMMENT '默认排序字段',
    default_sort_order VARCHAR(10) DEFAULT 'asc' COMMENT '默认排序方式:asc/desc',
    default_page_size INT DEFAULT 10 COMMENT '默认分页大小',
    page_size_options VARCHAR(256) DEFAULT '[10,20,50,100]' COMMENT '分页大小选项',
    show_pagination  TINYINT(1) DEFAULT 1 COMMENT '是否显示分页',
    show_refresh     TINYINT(1) DEFAULT 1 COMMENT '是否显示刷新按钮',
    show_column_setting TINYINT(1) DEFAULT 1 COMMENT '是否显示列设置',
    show_fullscreen  TINYINT(1) DEFAULT 1 COMMENT '是否显示全屏按钮',
    show_search_bar  TINYINT(1) DEFAULT 1 COMMENT '是否显示搜索栏',
    search_bar_position INT DEFAULT 1 COMMENT '搜索栏位置:1-顶部 2-右侧 3-隐藏',
    show_advanced_search TINYINT(1) DEFAULT 0 COMMENT '是否显示高级搜索',
    show_toolbar     TINYINT(1) DEFAULT 1 COMMENT '是否显示工具栏',
    show_add_button  TINYINT(1) DEFAULT 1 COMMENT '是否显示新增按钮',
    show_batch_add_button TINYINT(1) DEFAULT 0 COMMENT '是否显示批量新增按钮',
    show_edit_button TINYINT(1) DEFAULT 1 COMMENT '是否显示编辑按钮',
    show_delete_button TINYINT(1) DEFAULT 1 COMMENT '是否显示删除按钮',
    show_export_button TINYINT(1) DEFAULT 0 COMMENT '是否显示导出按钮',
    show_import_button TINYINT(1) DEFAULT 0 COMMENT '是否显示导入按钮',
    config           TEXT COMMENT '扩展配置(JSON)',
    remark           VARCHAR(512) COMMENT '备注',
    status           TINYINT(1) DEFAULT 1 COMMENT '状态:1-启用 0-禁用',
    tenant_id        VARCHAR(64) DEFAULT 'default' COMMENT '租户ID',
    create_time      DATETIME COMMENT '创建时间',
    create_user_id   VARCHAR(64) COMMENT '创建人ID',
    modify_time      DATETIME COMMENT '修改时间',
    modify_user_id   VARCHAR(64) COMMENT '修改人ID',
    is_deleted       TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    version          INT DEFAULT 0 COMMENT '版本号',
    UNIQUE KEY uk_entity_list_code (entity_id, list_code),
    INDEX idx_entity_id (entity_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据列表配置';

-- 元数据列表列配置
CREATE TABLE meta_list_column (
    column_id        VARCHAR(64) NOT NULL COMMENT '列ID' PRIMARY KEY,
    list_id          VARCHAR(64) NOT NULL COMMENT '列表配置ID',
    field_code       VARCHAR(64) NOT NULL COMMENT '字段编码',
    field_name       VARCHAR(128) NOT NULL COMMENT '字段名称',
    column_type      INT DEFAULT 1 COMMENT '列类型:1-普通列 2-排序列 3-图片列 4-标签列 5-开关列 6-按钮列 7-自定义列',
    width            INT COMMENT '列宽',
    min_width        INT COMMENT '最小列宽',
    align            INT DEFAULT 1 COMMENT '对齐方式:1-左对齐 2-居中 3-右对齐',
    fixed_left       TINYINT(1) DEFAULT 0 COMMENT '是否固定到左侧',
    fixed_right      TINYINT(1) DEFAULT 0 COMMENT '是否固定到右侧',
    sortable         TINYINT(1) DEFAULT 0 COMMENT '是否可排序',
    sort_field       VARCHAR(64) COMMENT '排序字段',
    filterable       TINYINT(1) DEFAULT 0 COMMENT '是否可筛选',
    filter_type      INT COMMENT '筛选类型:1-输入框 2-下拉框 3-日期范围 4-数字范围',
    filter_default_value VARCHAR(256) COMMENT '筛选默认值',
    dict_type_code   VARCHAR(64) COMMENT '字典类型编码',
    dict_data        TEXT COMMENT '字典数据(JSON)',
    image_preview    TINYINT(1) DEFAULT 0 COMMENT '图片预览',
    image_width      INT COMMENT '图片宽度',
    image_height     INT COMMENT '图片高度',
    date_format      VARCHAR(32) COMMENT '日期格式化',
    number_format    VARCHAR(32) COMMENT '数字格式化',
    show_in_list     TINYINT(1) DEFAULT 1 COMMENT '是否显示在列表中',
    show_in_default  TINYINT(1) DEFAULT 1 COMMENT '是否在默认列表中显示',
    config           TEXT COMMENT '扩展配置(JSON)',
    sort_order       INT DEFAULT 0 COMMENT '排序',
    tenant_id        VARCHAR(64) DEFAULT 'default' COMMENT '租户ID',
    create_time      DATETIME COMMENT '创建时间',
    create_user_id   VARCHAR(64) COMMENT '创建人ID',
    modify_time      DATETIME COMMENT '修改时间',
    modify_user_id   VARCHAR(64) COMMENT '修改人ID',
    is_deleted       TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    version          INT DEFAULT 0 COMMENT '版本号',
    INDEX idx_list_id (list_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据列表列配置';

-- 元数据列表按钮配置
CREATE TABLE meta_list_button (
    button_id        VARCHAR(64) NOT NULL COMMENT '按钮ID' PRIMARY KEY,
    list_id          VARCHAR(64) NOT NULL COMMENT '列表配置ID',
    button_code      VARCHAR(64) NOT NULL COMMENT '按钮编码',
    button_name      VARCHAR(128) NOT NULL COMMENT '按钮名称',
    button_type      INT DEFAULT 6 COMMENT '按钮类型:1-新增 2-编辑 3-删除 4-导出 5-导入 6-自定义',
    button_style     INT DEFAULT 1 COMMENT '按钮样式:1-主要 2-默认 3-文本 4-链接 5-成功 6-警告 7-危险 8-信息',
    icon             VARCHAR(64) COMMENT '图标',
    sort_order       INT DEFAULT 0 COMMENT '排序',
    visible          TINYINT(1) DEFAULT 1 COMMENT '是否显示',
    disabled         TINYINT(1) DEFAULT 0 COMMENT '是否禁用',
    click_event      VARCHAR(512) COMMENT '点击事件',
    permission_code  VARCHAR(128) COMMENT '权限编码',
    config           TEXT COMMENT '扩展配置(JSON)',
    tenant_id        VARCHAR(64) DEFAULT 'default' COMMENT '租户ID',
    create_time      DATETIME COMMENT '创建时间',
    create_user_id   VARCHAR(64) COMMENT '创建人ID',
    modify_time      DATETIME COMMENT '修改时间',
    modify_user_id   VARCHAR(64) COMMENT '修改人ID',
    is_deleted       TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    version          INT DEFAULT 0 COMMENT '版本号',
    INDEX idx_list_id (list_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据列表按钮配置';

-- 元数据列表查询条件配置
CREATE TABLE meta_list_query (
    query_id         VARCHAR(64) NOT NULL COMMENT '查询条件ID' PRIMARY KEY,
    list_id          VARCHAR(64) NOT NULL COMMENT '列表配置ID',
    field_code       VARCHAR(64) NOT NULL COMMENT '字段编码',
    field_name       VARCHAR(128) NOT NULL COMMENT '字段名称',
    query_type       INT DEFAULT 1 COMMENT '查询方式:1-精确查询 2-模糊查询 3-范围查询 4-日期范围 5-下拉框 6-多选',
    control_type     INT DEFAULT 1 COMMENT '控件类型:1-输入框 2-下拉框 3-日期选择 4-日期范围 5-数字范围 6-树选择',
    control_width    INT DEFAULT 200 COMMENT '控件宽度',
    placeholder      VARCHAR(256) COMMENT '占位符',
    default_value    VARCHAR(512) COMMENT '默认值',
    show_in_advanced TINYINT(1) DEFAULT 1 COMMENT '是否显示在高级搜索',
    show_in_quick    TINYINT(1) DEFAULT 1 COMMENT '是否显示在快速搜索',
    dict_type_code   VARCHAR(64) COMMENT '字典类型编码',
    sort_order       INT DEFAULT 0 COMMENT '排序',
    tenant_id        VARCHAR(64) DEFAULT 'default' COMMENT '租户ID',
    create_time      DATETIME COMMENT '创建时间',
    create_user_id   VARCHAR(64) COMMENT '创建人ID',
    modify_time      DATETIME COMMENT '修改时间',
    modify_user_id   VARCHAR(64) COMMENT '修改人ID',
    is_deleted       TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    version          INT DEFAULT 0 COMMENT '版本号',
    INDEX idx_list_id (list_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据列表查询条件配置';
