-- 元数据表配置
CREATE TABLE meta_table (
    id               VARCHAR(64) NOT NULL COMMENT '表ID' PRIMARY KEY,
    table_name       VARCHAR(128) NOT NULL COMMENT '表名称',
    table_desc       VARCHAR(256) COMMENT '表描述',
    table_type       INT DEFAULT 1 COMMENT '表类型:1-业务表 2-字典表 3-树形表 4-关联表',
    package_name     VARCHAR(128) COMMENT '包名',
    module_name      VARCHAR(64) COMMENT '模块名',
    class_name       VARCHAR(64) COMMENT '类名(首字母大写)',
    class_desc       VARCHAR(256) COMMENT '类描述',
    entity_name      VARCHAR(64) COMMENT '实体类名称',
    author           VARCHAR(64) COMMENT '作者',
    enabled          TINYINT(1) DEFAULT 1 COMMENT '是否启用:1-是 0-否',
    generated        TINYINT(1) DEFAULT 0 COMMENT '是否已生成:1-是 0-否',
    gen_path         VARCHAR(256) COMMENT '生成路径',
    remark           VARCHAR(512) COMMENT '备注',
    create_time      DATETIME COMMENT '创建时间',
    create_user_id   VARCHAR(64) COMMENT '创建人ID',
    modify_time      DATETIME COMMENT '修改时间',
    modify_user_id   VARCHAR(64) COMMENT '修改人ID',
    is_deleted       TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    version          INT DEFAULT 0 COMMENT '版本号',
    tenant_id        VARCHAR(64) DEFAULT 'default' COMMENT '租户ID',
    UNIQUE KEY uk_table_name (table_name),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据表配置';

-- 元数据实体配置
CREATE TABLE meta_entity (
    id               VARCHAR(64) NOT NULL COMMENT '实体ID' PRIMARY KEY,
    entity_code      VARCHAR(64) NOT NULL COMMENT '实体编码',
    entity_name      VARCHAR(128) NOT NULL COMMENT '实体名称',
    table_name       VARCHAR(128) COMMENT '物理表名',
    entity_type      VARCHAR(32) DEFAULT 'USER' COMMENT '实体类型:SYSTEM-系统 USER-自定义',
    category         VARCHAR(64) COMMENT '分类',
    description      VARCHAR(512) COMMENT '描述',
    package_name     VARCHAR(128) COMMENT '包名',
    module_name      VARCHAR(64) COMMENT '模块名',
    business_name    VARCHAR(64) COMMENT '业务名',
    template_type    VARCHAR(32) DEFAULT 'CRUD' COMMENT '模板类型:CRUD-增删改查 TREE-树形 MASTER_DETAIL-主明细',
    status           TINYINT(1) DEFAULT 1 COMMENT '状态:1-启用 0-禁用',
    create_time      DATETIME COMMENT '创建时间',
    create_user_id   VARCHAR(64) COMMENT '创建人ID',
    modify_time      DATETIME COMMENT '修改时间',
    modify_user_id   VARCHAR(64) COMMENT '修改人ID',
    is_deleted       TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    version          INT DEFAULT 0 COMMENT '版本号',
    tenant_id        VARCHAR(64) DEFAULT 'default' COMMENT '租户ID',
    UNIQUE KEY uk_entity_code (entity_code),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据实体配置';
