-- 元数据表单配置
CREATE TABLE meta_form (
    form_id          VARCHAR(64) NOT NULL COMMENT '表单配置ID' PRIMARY KEY,
    entity_id        VARCHAR(64) NOT NULL COMMENT '实体ID',
    form_code        VARCHAR(64) NOT NULL COMMENT '表单编码',
    form_name        VARCHAR(128) NOT NULL COMMENT '表单名称',
    form_type        INT DEFAULT 1 COMMENT '表单类型:1-默认表单 2-弹窗表单 3-抽屉表单 4-步骤表单',
    layout           INT DEFAULT 1 COMMENT '表单布局:1-单列 2-双列 3-三列 4-四列',
    width            INT DEFAULT 600 COMMENT '表单宽度',
    label_position   INT DEFAULT 1 COMMENT '表单标签位置:1-左侧 2-上方 3-右侧',
    label_width      INT DEFAULT 100 COMMENT '表单标签宽度',
    show_buttons     TINYINT(1) DEFAULT 1 COMMENT '是否显示操作按钮',
    show_reset_button TINYINT(1) DEFAULT 1 COMMENT '是否显示重置按钮',
    show_cancel_button TINYINT(1) DEFAULT 1 COMMENT '是否显示取消按钮',
    submit_button_text VARCHAR(32) DEFAULT '提交' COMMENT '提交按钮文本',
    reset_button_text VARCHAR(32) DEFAULT '重置' COMMENT '重置按钮文本',
    cancel_button_text VARCHAR(32) DEFAULT '取消' COMMENT '取消按钮文本',
    submit_action    INT DEFAULT 1 COMMENT '提交后行为:1-关闭弹窗 2-刷新列表 3-跳转页面',
    redirect_path    VARCHAR(256) COMMENT '跳转页面路径',
    config           TEXT COMMENT '扩展配置(JSON)',
    remark           VARCHAR(512) COMMENT '备注',
    status           TINYINT(1) DEFAULT 1 COMMENT '状态:1-启用 0-禁用',
    tenant_id        VARCHAR(64) DEFAULT 'default' COMMENT '租户ID',
    create_time      DATETIME COMMENT '创建时间',
    create_user_id   VARCHAR(64) COMMENT '创建人ID',
    modify_time      DATETIME COMMENT '修改时间',
    modify_user_id   VARCHAR(64) COMMENT '修改人ID',
    is_deleted       TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    version          INT DEFAULT 0 COMMENT '版本号',
    UNIQUE KEY uk_entity_form_code (entity_id, form_code),
    INDEX idx_entity_id (entity_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据表单配置';

-- 元数据表单字段配置
CREATE TABLE meta_form_field (
    field_id         VARCHAR(64) NOT NULL COMMENT '字段ID' PRIMARY KEY,
    form_id          VARCHAR(64) NOT NULL COMMENT '表单配置ID',
    field_code       VARCHAR(64) NOT NULL COMMENT '字段编码',
    field_name       VARCHAR(128) NOT NULL COMMENT '字段名称',
    field_type       VARCHAR(32) COMMENT '字段类型',
    control_type     INT DEFAULT 1 COMMENT '控件类型:1-输入框 2-文本域 3-下拉框 4-单选框 5-复选框 6-开关 7-日期选择 8-时间选择 9-日期时间选择 10-文件上传 11-图片上传 12-富文本 13-评分 14-滑块 15-颜色选择 16-穿梭框 17-树选择',
    control_width    INT DEFAULT 100 COMMENT '控件宽度(百分比)',
    placeholder      VARCHAR(256) COMMENT '占位符',
    default_value    VARCHAR(512) COMMENT '默认值',
    required         TINYINT(1) DEFAULT 0 COMMENT '是否必填',
    editable         TINYINT(1) DEFAULT 1 COMMENT '是否可编辑',
    visible          TINYINT(1) DEFAULT 1 COMMENT '是否可见',
    copyable         TINYINT(1) DEFAULT 0 COMMENT '是否可复制',
    rules            TEXT COMMENT '验证规则(JSON)',
    dict_type_code   VARCHAR(64) COMMENT '字典类型编码',
    dict_data        TEXT COMMENT '字典数据(JSON)',
    remote_url       VARCHAR(512) COMMENT '远程数据URL',
    label_field      VARCHAR(64) COMMENT '显示字段',
    value_field      VARCHAR(64) COMMENT '值字段',
    group_name       VARCHAR(128) COMMENT '分组名称',
    sort_order       INT DEFAULT 0 COMMENT '排序',
    config           TEXT COMMENT '扩展配置(JSON)',
    tenant_id        VARCHAR(64) DEFAULT 'default' COMMENT '租户ID',
    create_time      DATETIME COMMENT '创建时间',
    create_user_id   VARCHAR(64) COMMENT '创建人ID',
    modify_time      DATETIME COMMENT '修改时间',
    modify_user_id   VARCHAR(64) COMMENT '修改人ID',
    is_deleted       TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    version          INT DEFAULT 0 COMMENT '版本号',
    INDEX idx_form_id (form_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据表单字段配置';
